name: learn-github-actions
on: [push]
env: 
  _ENV_FILE: ${{ secrets._ENV_FILE}}
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "$_ENV_FILE" | base64 -d > .env
          whoami
          docker build . -t docker.takatsuki.club/tepic-kra:latest
          docker rm -f tepic-kra
          docker run --name tepic-kra --restart=always -d docker.takatsuki.club/tepic-kra:latest
